version: "3.9"

networks:
  proxy:
    external: true
    name: proxy-web

services:
  httpd:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VIRTUAL_HOST: default
    networks:
      - proxy