version: "3.9"

networks:
  default:
    external: true
    name: proxy-web

volumes:
  nginx-dhparam:
  nginx-certs:
  nginx-config:

services:
  nginx-proxy:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: nginx-config
        target: /etc/nginx/conf.d
      - type: volume
        source: nginx-dhparam
        target: /etc/nginx/dhparam
      - type: volume
        source: nginx-certs
        target: /etc/nginx/certs

  docker-gen:
    build:
      context: .
    volumes:
      - type: volume
        source: nginx-config
        target: /etc/nginx/conf.d
      - type: volume
        source: nginx-dhparam
        target: /etc/nginx/dhparam
      - type: volume
        source: nginx-certs
        target: /etc/nginx/certs
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
    environment:
      DEFAULT_HOST: default
    pid: service:nginx-proxy